# Generated by Django 2.2.3 on 2019-07-25 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapingbackend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrap',
            name='year',
            field=models.DecimalField(decimal_places=2, max_digits=1000, null=True),
        ),
    ]
